# Generated by Django 4.2.5 on 2023-09-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_projectsinportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='contact_email',
            field=models.CharField(max_length=200, verbose_name='Contact Email'),
        ),
    ]
