# Generated by Django 4.2.5 on 2023-10-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_portfolio_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsInPortfolio',
        ),
    ]
